### ISSUE TITLE
More explanations?

### ISSUE THREAD

**Issue by JaninaPi** [raspberrypilearning/python-web-server-with-flask#20]
The way this is written at the moment doesn't explain a lot of the terminology and logic. Not sure what level this project is aimed at, but I think if you added in more definitions and some real-life examples, that would help a lot.

- What actually is a web server?
- Are a web app and a web server the same thing?
- What's a request?
- Is the index of the website the homepage, and is the homepage the root?
- What's a route? Is it just a URL? What's the difference between a route and a web page?
- What's a template? Is it different from a regular HTML file?
- What exactly is the difference between static and dynamic content?

**Comment by martinohanlon** [comment]
Thanks @JaninaPi 
@MarcScott - I have re-assigned this to me (from @caitlynraspberrypi) as the issues are on the back of some changes I made.

**Comment by martinohanlon** [comment]
@JaninaPi This is a developer level project and as such we can assume a level of knowledge relating to how the "web" works, however, I share your views about the project needing some additional information / tidying.

I have: 
- added some additional content to give pointers to the relationships between web servers, sites and applications, routes, etc
- made the use of such terms consistent throughout the project
- simplified the language used and the headings for the steps
- other bits and bobs tidying up and [hopefully] making it easier to understand
