### ISSUE TITLE
Error running python3 app.py

### ISSUE THREAD

**Issue by libxx1** [raspberrypilearning/python-web-server-with-flask#24]
URL: /en/projects/python-web-server-with-flask/1

when I run: python3 app,py for the web server project I get the following

pi@raspberrypi:~ $ cd webapp
pi@raspberrypi:~/webapp $ python3 app.py
 * Running on http://0.0.0.0:5000/
 * Restarting with reloader

**Comment by anselal** [comment]
can't you access the page at http://localhost:5000 ?

**Comment by libxx1** [comment]
Works on mac will try on Pi

**Comment by libxx1** [comment]
Closing issue as can't replicate error on mac or Raspberry Pi. User entered feedback anonymously so can't get anymore information from them to investigate further.
