### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/python-web-server-with-flask#3]
@MissPhilbin @jrobinson-uk @MarcScott can one of you have a go through the worksheet please?

**Comment by bennuttall** [comment]
@lauraclay @LornaLynch does one of you have time to run through the worksheet to make sure the steps work?

**Comment by LornaLynch** [comment]
I have some MagPi stuff I have to prioritise, but I'll try to get to it ASAP.

**Comment by bennuttall** [comment]
@LornaLynch Did you test this one too?

**Comment by LornaLynch** [comment]
I checked the worksheet text, but I haven't actually run through the steps. I can do this now if you need.

**Comment by LornaLynch** [comment]
Are you going to make it live now, or do you want to hang on until I have worked through?

**Comment by bennuttall** [comment]
@gbaman1 has run through it and says it works so I've made it live but if you could too it would help.

Thanks

**Comment by LornaLynch** [comment]
I will do. I'll close this issue when I'm done.

**Comment by LornaLynch** [comment]
Question regarding the dynamic content section: in the section of code which gets the website to say hello to the entered name, the code in the textbox (regarding the variable) reads `def hello(name)`, but in the notes, it reads `def name(my_name)` Is there a line missing somewhere, or are the notes wrong? The code in the box worked fine, btw.

**Comment by bennuttall** [comment]
That's a mistake - fixed, thanks

**Comment by LornaLynch** [comment]
Thanks! I think it's all OK now.
