### ISSUE TITLE
Add cover image

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/python-web-server-with-flask#5]
Hey @samalderhyde can you create two variations of the [WordPress Web Server resource cover](https://github.com/raspberrypilearning/web-server-wordpress/blob/master/cover.png)? One for WordPress and one for Flask?

The main theme would stay the same but they would incorporate a subtle difference - the logo or equivalent, and a change in background colour would be good.
- **LAMP/WordPress could incorporate any of the following:**
  - a [lamp](https://www.google.com/search?q=lamp&tbm=isch)
  - the [PHP logo](https://www.google.com/search?q=lamp&tbm=isch#tbm=isch&q=php+logo) or an elephant
  - the [WordPress logo](https://www.google.com/search?q=lamp&tbm=isch#tbm=isch&q=wordpress+logo)
- **Python/Flask could incorporate any of the following:**
  - the [Python logo](https://www.google.com/search?q=lamp&tbm=isch#tbm=isch&q=python+logo)
  - a snake
  - a [flask](https://www.google.com/search?q=lamp&tbm=isch#tbm=isch&q=python+flask)

Does that sound ok?

**Comment by samalderhyde** [comment]
Sounds fine, I'll take a look at it ASAP. When would you need it by? soon as?

**Comment by bennuttall** [comment]
Yeah whenever you get chance! Thanks

**Comment by bennuttall** [comment]
@samalderhyde

**Comment by lawsie** [comment]
The resource appears to have cover art, so closing this issue.

**Comment by bennuttall** [comment]
The issue is the cover for this a duplicate of https://github.com/raspberrypilearning/lamp-web-server-with-wordpress

**Comment by martinohanlon** [comment]
Raised issue for new banner. https://github.com/raspberrypilearning/Comms/issues/1172

**Comment by martinohanlon** [comment]
new cover image created.
