### ISSUE TITLE
Testing Feedback

### ISSUE THREAD

**Issue by MissPhilbin** [raspberrypilearning/python-web-server-with-flask#6]
1. Step 2.7 the messaged returned was different from: 
```
- Running on http://0.0.0.1:5000/
- Restarting with reloader
```
mine reads ```Restarting with stat```. This did not effect the outcome. Not sure if it matters? 

2. Recommend using gender neutral name instead of "Paul".

**Comment by bennuttall** [comment]
1. Fixed
1. It was Paul because @phalt originally wrote the resource. We could change it but I'd have to change the screenshot.

**Comment by phalt** [comment]
Totally fine for you to change it :+1:
